name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master       # your default branch
  workflow_dispatch:  # manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages@v4
        with:
          path: ./build   # your custom build output folder
          name: github-pages

  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: .
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
